### ISSUE TITLE
Client Sell-10 currently executes Sell-All

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#107]
& When buying items all items disappear

**Comment by Gptaqbc** [comment]
What do you mean by string needs to be fixed?

**Comment by RedSparr0w** [comment]
Menu item needs to be modified:
`Sell 5` -> `Sell 10`
`Sell 10` → `Sell All`

**Comment by Gptaqbc** [comment]
Oh alright. I'll do that!

**Comment by Gptaqbc** [comment]
You got any hint about where I have to look? Looking for Sell 10 doesn't give anything.

**Comment by RedSparr0w** [comment]
Not sure sorry, haven't looked into any of the client sided things yet.

**Comment by Gptaqbc** [comment]
RSInterface.java

Sell 1 → 1
Sell 5 → 10
Sell 10 → All

Code to modify: around line 108...
This add a sell all option... it needs some work done though.
if(rsInterface.parentID == shop interface id) rsInterface.itemActions[buy all menu action number] = "Sell All";

**Comment by Gptaqbc** [comment]
To do: 
1.Replace Buy 10 by buy all - Server side;
2.Fix selling options that currently only sells 1 at a time;

**Comment by RedSparr0w** [comment]
Not sure what you mean by `2`?
I'm pretty sure we replaced the loop that it used to use.

**Comment by Gptaqbc** [comment]
@RedSparr0w  Yeah it needed some work because it was causing lag when buying more than a couple item at once.
