### ISSUE TITLE
On account creation character weight is too high

### ISSUE THREAD

**Issue by RedSparr0w** [dginovker/2006rebotted#109]
When you first create an account, your weight will show `32kgs` even though all your items only adds upto `16kgs`.
when you drop all your items, you will still be carrying `16kgs`.

This is fixed by relogging in.

I assume on account creation the characters item weight is set to 16kgs, and then the items weight is added on top of that.
once relogging, it is recalculated correctly.

**Comment by Dark98** [comment]
This is due to weight calculation being run two for new accounts, once during each item from the starter being added to the inv & then again after(which would be the normal login weight calculation)
