### ISSUE TITLE
When buying items all items disappear 

### ISSUE THREAD

**Issue by RedSparr0w** [dginovker/2006rebotted#115]
When buying player sold items from a store (general store for example)
If you buy any amount of items, the whole stack will disappear.

**Comment by Gptaqbc** [comment]
It only happens if the stack was sold using the sell all option IIRC

**Comment by RedSparr0w** [comment]
seems to happen with any amount sold.

**Comment by Gptaqbc** [comment]
Is it possible to merge that issue with the #107? I got this fixed in my work in progress.

**Comment by dginovker** [comment]
Closed for #107

**Comment by RedSparr0w** [comment]
You don't need to be assigned an issue to work on it 😄 
When you create the PR what you would usually do is write the following:

Closes #107 
Closes #115

Which would close the 2 issues once your PR is merged
Better to keep the issue open until they are actually fixed, otherwise they can get missed quite easily.

**Comment by Gptaqbc** [comment]
It’s not that I want or need to be assigned. It’s that I dont want other contributors to start working on it while I am too. So no one is working for nothing a.k.a wasting their time.

**Comment by RedSparr0w** [comment]
Yeah, once the comment is there other people *should* notice someone is already working on it, just saying better to keep the issues open until they are actually fixed.

**Comment by Gptaqbc** [comment]
Oh yeah, that’s sure. Issues have to stay open until completely resolved. I just asked to merge 2 issues together because It was related to the same problem.

**Comment by RedSparr0w** [comment]
But they are separate problems, they may be similar/have a similar fix, but they are quite different problems.

**Comment by Gptaqbc** [comment]
What should I do then? I dont want someone working on that because it’s fixed on my side.

**Comment by RedSparr0w** [comment]
Just comment here, and put it on your PR when you create it. the same thing you would do on the other issue.
