### ISSUE TITLE
Object interaction distance is improper

### ISSUE THREAD

**Issue by mikeysasse** [dginovker/2006rebotted#116]
Objects actions are executed before you reach the object

**Comment by DPSCryptic** [comment]
this is already known :P but goodjob

**Comment by mikeysasse** [comment]
Sorry I didn't see it in the issues, remove this if necessary. I'll work on fixing this one for my first pull request.

**Comment by DPSCryptic** [comment]
indeed, its not in the issues, thanks for adding it
