### ISSUE TITLE
When pressing 'run' button character doesn't run until clicking walk again

### ISSUE THREAD

**Issue by mikeysasse** [dginovker/2006rebotted#127]

**Comment by Gptaqbc** [comment]
This isn't true... or at least can't be replicated.

If this is talking about the fact that you have to click the minimap/ground after clicking run to actually be running, I think it was like that in 2006.

**Comment by DPSCryptic** [comment]
tbh i dont think it was, and even if so, it is just weird :/

**Comment by Gptaqbc** [comment]
This can also be closed @dginovker
