### ISSUE TITLE
It seems like NPCs in wildy aren't aggressive.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#132]
Strange because we've got this already:

NpcAggressive.java (line 26)
		if (NpcHandler.npcs[i].inWild() && NpcHandler.npcs[i].MaxHP > 0) {
			return true;
		}

Maybe the public boolean inWild() in NPC.java isn't working properly.

**Comment by Gptaqbc** [comment]
Strange because we've got this already:

NpcAggressive.java (line 26)
		if (NpcHandler.npcs[i].inWild() && NpcHandler.npcs[i].MaxHP > 0) {
			return true;
		}

**Comment by Gptaqbc** [comment]
Maybe the public boolean inWild() in NPC.java isn't working properly.

**Comment by RedSparr0w** [comment]
Only npcs so far that have been aggressive towards me in the wild are the greater demons and ice warriors, but i believe they are already aggressive.

**Comment by mrextremez** [comment]
Seems like something may be blocking them from being aggressive. I can look into it later when I have time

**Comment by mrextremez** [comment]
Should be fixed now @dginovker
