### ISSUE TITLE
List of objects not working properly (Add any door/gate/portal/... that isn't working in here please)

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#139]

**Comment by Gptaqbc** [comment]
Portal in the pyramid with the ancient altar doesn't do anything. It should teleport you outside the pyramid.

**Comment by Gptaqbc** [comment]
#6

**Comment by Gptaqbc** [comment]
Gates at KBD.

**Comment by Dark98** [comment]
You should add these as separate issues so they can be closed one by one as they get fixed, it'll be easier to keep track of the current broken/fixed ones that way

**Comment by Gptaqbc** [comment]
Ranging guild door isn't opening properly. When opened it's still in the way.
