### ISSUE TITLE
Scorpions under Falador are aggressive no matter your combat level

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#142]
The Scorpions level 14 and 32 at the mining spot under Falador.

**Comment by mrextremez** [comment]
I can fix this

**Comment by dginovker** [comment]
Everything is aggressive right now :thinking:

**Comment by Gptaqbc** [comment]
Buuut the scorpions arent aggresive to any clmb lvl anymore :)

**Comment by Gptaqbc** [comment]
@mrextremez I think your fix will solve this issue too.

**Comment by mrextremez** [comment]
I posted a new fix for this
