### ISSUE TITLE
Longrange attack style seems to have the same range as the other attack type

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#146]

**Comment by Dark98** [comment]
It's supposed to isn't it? It just trains defence exp too

**Comment by dginovker** [comment]
Nope, crossbows/shortbos/longbows on Long Ranged should have further reach: https://oldschoolrunescape.fandom.com/wiki/Longbow

**Comment by Gptaqbc** [comment]
It's supposed to boost attack range by 2 squares.
