### ISSUE TITLE
Logout panel and login screen still reference "2006redone"

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#148]
As seen in Agility's humorous video: https://gyazo.com/c0eaa4def1020e196e7975ef740ed48a

Update: Some references have been fixed, others still exist

**Comment by RedSparr0w** [comment]
Same thing with the bank
![image](https://user-images.githubusercontent.com/7288322/68534893-f4808180-039e-11ea-9254-87454bd0674b.png)

**Comment by Dark98** [comment]
this has been fixed :p
