### ISSUE TITLE
Server still crashes with woodcutting

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#15]
https://cdn.discordapp.com/attachments/600783404392251403/630425592298340352/unknown.png

That's the stacktrace

**Comment by dginovker** [comment]
Closed with https://github.com/dginovker/2006rebotted/pull/16

**Comment by benmaher95** [comment]
Re-open please <3

**Comment by benmaher95** [comment]
Looking good so far, no issues since second fix yet.

**Comment by dginovker** [comment]
Thanks for the double fix. Closing :)
