### ISSUE TITLE
NPCs in underground must be aggressive if your combat level isn't > than 2x their combat level.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#160]

**Comment by Gptaqbc** [comment]
Also rock crabs arent aggressive anymore

**Comment by mrextremez** [comment]
This is the case for all underground npcs @Gptaqbc or can you provide a list of which npcs.

**Comment by Gptaqbc** [comment]
All underground npcs

**Comment by Gptaqbc** [comment]
like skeletons and zombies

**Comment by mrextremez** [comment]
Are you sure? @Gptaqbc you could be right but im not 100% sure on that

**Comment by Gptaqbc** [comment]
Well I walked in an underground full of npcs lvl 21 and 49. I was level 2 and never got attacked.

**Comment by mrextremez** [comment]
I made some modifications, I will test it locally and will push it out in a bit.
