### ISSUE TITLE
Add ::gfxtgl to ::commands

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#167]
::gfxtgl disables rendering graphics, saving CPU usage

~~~ Useful when running a lot of clients as it should lower the CPU usage. ~~~

**Comment by dginovker** [comment]
Fixed in #168, edited title for new minor goal

**Comment by dginovker** [comment]
We kinda changed what the issue was about, just to complete it @RedSparr0w . We just need to add it to ::commands now:
![image](https://user-images.githubusercontent.com/32943174/68595832-3b867980-0468-11ea-91e4-e59c8f0de1f8.png)

**Comment by Gptaqbc** [comment]
Could we rename it so it more explicitely says what it does? Like ::ToggleRendering or anything that isn't a bunch of letter?

**Comment by dginovker** [comment]
Yeah just add that to the switch statement
