### ISSUE TITLE
Axe visually changes to different axe when woodcutting

### ISSUE THREAD

**Issue by DPSCryptic** [dginovker/2006rebotted#173]

**Comment by Gptaqbc** [comment]
@JetF0x Could you add more information to the issue if you got more? :) Thanks!

**Comment by JetF0x** [comment]
I've got literally no idea why it happens, maybe when tree is cut down with multiple people chopping it switches anims? @Gptaqbc

**Comment by mrextremez** [comment]
Is this on the local client aswell? Or only on bot client?

**Comment by Gptaqbc** [comment]
I was able to replicate this bug and also got the anim with a rune axe. I was cutting a tree at Lumbridge with a bronze axe. 

Is it only happening with a bronze axe?

**Comment by DPSCryptic** [comment]
which anim?

**Comment by Gptaqbc** [comment]
I have a theory. This seems to only be happening with 2006 AIO. I noticed that the woodcutting script spam clicks the trees. I think that when spam clicking the trees it fucks something somewhere before launching the wcing animation. @RedSparr0w  Could you tell me if this makes sense?
