### ISSUE TITLE
Wizard Tower Doors

### ISSUE THREAD

**Issue by JetF0x** [dginovker/2006rebotted#174]
Wizard Tower Doors are broken.

**Comment by Gptaqbc** [comment]
After talking in Discord about this issue it seems like:

> This door is special as using it should make your player open the door, walk through the tile and close the door.
> We can see the door is opening and closing so the issue is most likely related to the walkTo method as @Michael said in discord.
> A couple of doors are supposed to work like that.

**Comment by Gptaqbc** [comment]
@mikeysasse Was solved?

**Comment by Gptaqbc** [comment]
@JetF0x If you got time or you are passing by, could you retry and close the issue if it's resolved? :)

**Comment by JetF0x** [comment]
Fixed-ish, next step just make it so doors don't disappear when clicking on them sometime?

**Comment by Gptaqbc** [comment]
That a new issue. Close this one.
