### ISSUE TITLE
Al Kharid furnace is not working at all.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#177]
The furnace at Falador works.

**Comment by mrextremez** [comment]
does it have a different object id?

**Comment by Gptaqbc** [comment]
This could be related to the distance between the player and the object.

**Comment by mrextremez** [comment]
Increase the object size

**Comment by Gptaqbc** [comment]
Whatcha mean?

**Comment by mrextremez** [comment]
getObjectSize(), objects.java.

Easiest way is just to manually increase object size for the furnace so the player can reach the object

**Comment by dginovker** [comment]
What do you use to edit the cache, @mrextremez ? If I'm understanding this right we have to edit it there
