### ISSUE TITLE
There is a shitload of maple trees somehow spawning on the map and they dissapears when you log back in...???

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#179]

**Comment by dginovker** [comment]
If I recall correctly this was from Jetfox's woodcutting script. If he can open source it we can see what commands he's calling to make this happen

**Comment by JetF0x** [comment]
Click tree, wait til animation == -1, cut new tree.

**Comment by dginovker** [comment]
Welp

**Comment by Gptaqbc** [comment]
There is also some trees in edgeville underground.

**Comment by Gptaqbc** [comment]
This is still relevant but there ain't many player using @JetF0x scripts as I can see on the server. We have to figure out how the trees keep spawning everywhere his bots goes.

**Comment by JetF0x** [comment]
I haven't had any woodcutters going all week...

**Comment by Gptaqbc** [comment]
When I was in edge underground there was a lot of trees in there too @JetF0x. It's most likely not related to you but it's strange that the issue appeared with your scripts so that's why we are talking about you.
