### ISSUE TITLE
When wearing a black full helm (g) the hair of your player aren't removed so it looks wack.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#180]
Dont know if it's all full helm that does that. I know for sure that the black full helm (g) does it though.

**Comment by mrextremez** [comment]
Look for item.java method fullmask I think if you add it there it might work

**Comment by Gptaqbc** [comment]
To fix add "full helm (g)", "full helm (t)" to the following array:

/* Fullmask covers your entire head. */
	private static String[] fullmask = { "full helm", "mask", "Verac's helm",
			"Guthan's helm", "Karil's coif", "mask", "Torag's helm", "Void",
			"sallet", "Facemask" };

Do the same for the items that aren't added to its corresponding array.

**Comment by Gptaqbc** [comment]
Fixed gotta push
