### ISSUE TITLE
Spam clicking an oak tree result in obtaining a lot of logs really fast

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#183]

**Comment by mrextremez** [comment]
Read my comment on #184

**Comment by mikeysasse** [comment]
Easiest fix would be to replace the main cycle event with Player#setCurrentTask

**Comment by Gptaqbc** [comment]
https://www.rune-server.ee/runescape-development/rs2-server/help/527334-spam-clicking-problem.html

**Comment by dginovker** [comment]
Fixed with Captcha's link. Added:

`CycleEventHandler.getSingleton().stopEvents(player, "WoodcuttingEvent".hashCode());`

To the start woodcutting function.
