### ISSUE TITLE
Spam clicking a tree fast enough will D/C everyone.

### ISSUE THREAD

**Issue by JetF0x** [dginovker/2006rebotted#184]

**Comment by mrextremez** [comment]
Add a simple timer when clicking the tree to prevent this

**Comment by Gptaqbc** [comment]
Players can still abuse it.

**Comment by Gptaqbc** [comment]
Most likely an out of bound shitty error. @dginovker  can you provide any error message about this?

**Comment by dginovker** [comment]
Leveling up an acc for oak trees right now. On normal trees, you get this message though, just no logs or EXP:

![image](https://user-images.githubusercontent.com/32943174/68957742-a998ac80-0798-11ea-9b76-1f60e13d95a2.png)

**Comment by Gptaqbc** [comment]
mmmm I've had this message on my localhost too when cutting logs.

**Comment by Gptaqbc** [comment]
Is this happening when cutting a tree that gets cut by another account before you can finish cutting it on the first account?

**Comment by dginovker** [comment]
Nope I'm only one in area.

**Comment by Gptaqbc** [comment]
Is it clicking the tree more than once then?

**Comment by dginovker** [comment]
Yup, spam clicking it. You should be able to reproduce locally

**Comment by Gptaqbc** [comment]
It seems like it's sending actions to do when it doesnt have to. Maybe it's sending a packet to cut the tree but it just got cutted.

**Comment by Gptaqbc** [comment]
When clicking a tree, before doing an action, check if the action is already what the player is doing. Don't send packet or something if the action is already been done. This would resolve the packet spam issue I think.

**Comment by Gptaqbc** [comment]
Launching this: 
>CycleEventHandler.getSingleton().addEvent("WoodcuttingEvent".hashCode(), player, new CycleEvent() {

only when it's not already what the player is doing.

**Comment by dginovker** [comment]
I actually added that code in my last PR, @Gptaqbc . It fixes the spam clicking oaks gives infinite logs bug, it may have actually also solved this. The reason we hash "WoodcuttingEvent", is so when it goes into the EventHandler it removes any previous instance of this.

If this is what your idea of fixing it was, it may already work and this issue is ready to close. Don't get confused thinking that code was already there and this issue was still reported with it O_O

**Comment by Gptaqbc** [comment]
Yeah I know ubt it didnt solve this I just tried. Server crach at 3000ish clicks.

**Comment by Gptaqbc** [comment]
The 300ms restriction that was added earlier last week fix this issue.
