### ISSUE TITLE
Shouldn't be able to sell to a shop when there is not empty slot in the shop interface.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#194]
As of right now you can sell more than max capacity and it causes any player that uses the store to disconnect.

**Comment by Gptaqbc** [comment]
Working on it!

**Comment by mrextremez** [comment]
What work is left to be done? @Gptaqbc

**Comment by Gptaqbc** [comment]
Code must be added to prevent players from selling items to gen store when it's full and not already in shop.

The tricky part I saw was that you have to check the shop if the items is already in a slot.

**Comment by RedSparr0w** [comment]
This should be fixed by PR #idontknowthenumber
