### ISSUE TITLE
Sometimes your player will do an action and stay "busy" so it'll be unable to trade with other players.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#198]
I have no idea which actions leaves you busy so if you have any hint just let me know please!

Temporary fix: relog

**Comment by Gptaqbc** [comment]
Was able to reproduce yesterday. It seems to be related to opening a shop and doing something in it. Have to confirm though.

**Comment by mrextremez** [comment]
I tried and was not able to encounter this issue
