### ISSUE TITLE
Shift-Drop doesn't work on objects who's first option isn't "use"

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#2]
Update: Gptaqbc is on it

**Comment by dginovker** [comment]
https://github.com/dginovker/2006rebotted/blob/master/2006Redone%20Client/src/Game.java#L1172

https://www.rune-server.ee/runescape-development/rs2-client/snippets/651304-shift-click-dropping.html

Possibly relevant

**Comment by Gptaqbc** [comment]
Note:
If you press shift and right click an item you can see that the drop option is there twice. So in the code where it says change use for drop there should be a condition for if there is a wear option to change this one instead.

**Comment by Gptaqbc** [comment]
Ahh I was hoping there would be something like that:

if (shiftDown)
											{
												menuActionName[menuActionRow] = "Drop @lre@" + itemDef.name;
											} else {
												menuActionName[menuActionRow] = "Use @lre@" + itemDef.name;
											}

But for the wear option... But there isn't. 

I'm looking at it for a bit.

**Comment by DPSCryptic** [comment]
make the option :P

**Comment by Gptaqbc** [comment]
Yep, I'm trying to figure it out simply :P

**Comment by Gptaqbc** [comment]
menuActionName[menuActionRow] = itemDef.actions[i4] + " @lre@" + itemDef.name;
													if (i4 == 0) {
														menuActionID[menuActionRow] = 74;
													}
													if (i4 == 1) {
														menuActionID[menuActionRow] = 454;
													}
													if (i4 == 2) {
														menuActionID[menuActionRow] = 539;
													}


I4 contains the options of the items but do you guys know what 74, 454 and 539 are?

**Comment by DPSCryptic** [comment]
where do you find this?

**Comment by Gptaqbc** [comment]
Here: https://github.com/dginovker/2006rebotted/blob/master/2006Redone%20Client/src/Game.java#L1172

**Comment by DPSCryptic** [comment]
this is in there

**Comment by Gptaqbc** [comment]
So 447 seems like to be the use option?

**Comment by DPSCryptic** [comment]
yeah probably

**Comment by DPSCryptic** [comment]
just talk in discord will ya

**Comment by Gptaqbc** [comment]
Sweet, we are getting closer and closer. I'll have to do some testing when I get home. Don't have Discord at work, sorry.

**Comment by DPSCryptic** [comment]
way easier than this

**Comment by DPSCryptic** [comment]
wdym discord is also a web app >.<

**Comment by Gptaqbc** [comment]
Commenting here is helpful because it stays here.

Bro, it's blocked.

**Comment by DPSCryptic** [comment]
but this spams the updates in discord, so not so usefull

**Comment by Gptaqbc** [comment]
If it wan't useful to add notes to issues the option wouldn't be on here. 

It's better to have more informations about an issue in the issue post instead of it being on a chat that keeps growing.

**Comment by Gptaqbc** [comment]
But I get your point about the spam. It's shit that every post gets psoted on the discord.

**Comment by DPSCryptic** [comment]
this aint usefull information, this is just chatting

**Comment by DPSCryptic** [comment]
alright, now keep the comments about the issue and not chat alright :P

**Comment by Gptaqbc** [comment]
Yep, let's delete our shit post.
