### ISSUE TITLE
Lumbridge teleports requires wrong magic level

### ISSUE THREAD

**Issue by DPSCryptic** [dginovker/2006rebotted#219]

**Comment by Gptaqbc** [comment]
It should require level 20 mage to be casted. Right now I think it's 35.

**Comment by DPSCryptic** [comment]
no, it requires 32 now and needs to be 31

**Comment by mrextremez** [comment]
Fixed now or still needs to be changed?

**Comment by mrextremez** [comment]
Can be closed now
