### ISSUE TITLE
Cannonballs sold by the NPC at the entrance of the Dwarf underground are sold for 5gp each.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#230]
They should be higher price(back in 2006 they were averaging 150-200gp each when sold by players)  and the cannonball mould should also be sold in this shop for 5gp.

I'm not even sure it was possible to buy cannonballs from this shop in 2006.

**Comment by DPSCryptic** [comment]
were they ever sold?

**Comment by DPSCryptic** [comment]
cant find anything about them being in a store

**Comment by DPSCryptic** [comment]
there should just be a cannon and mould if i recall correctly

**Comment by Gptaqbc** [comment]
Yeah that's what I'm trying to say lol
