### ISSUE TITLE
Retrieving cannon got some fix needed.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#232]
When retrieving cannong with less than 4 inventory spaces you lose pieces as they cant get in your inventory or on the ground; Should make it so you cant retrieve with less than 4  empty inventory spaces.

When login back in game after losing a cannon a chat message appear saying "You can collect your cannon at home from Nulodion"; Nulodion isn't at home.

**Comment by mrextremez** [comment]
This is fixed

**Comment by RedSparr0w** [comment]
Awesome thanks
