### ISSUE TITLE
Pickpocketing Server Crash

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#233]
![image](https://user-images.githubusercontent.com/32943174/70201253-0a563d80-16e4-11ea-9e43-686e7097f281.png)

**Comment by dginovker** [comment]
RedSparr0w was pickpocketing the Drunk Man in upstairs Falador

**Comment by dginovker** [comment]
Seems to be fixed in https://github.com/dginovker/2006rebotted/commit/402d732975c559096d49ccfc440df745d75ec6ca

**Comment by dginovker** [comment]
Nevermind, still occurring

**Comment by RedSparr0w** [comment]
Line 205 at the time of the crash:

https://github.com/dginovker/2006rebotted/blob/256452114cd30c609817d672907f7056ee46dba6/2006Redone%20Server/src/com/rebotted/game/content/skills/thieving/Pickpocket.java#L205

Looks like the npc doesn't exist or something? not really sure how this would occur.

**Comment by mrextremez** [comment]
Which npc did it crash with?

**Comment by RedSparr0w** [comment]
Forgotten the ID, but it was the drunk man upstairs in falador
