### ISSUE TITLE
3 potato cactus spawns on the ground near kalphite queen

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#236]
They simply shouldnt be spawning there.

ID: 3138

Locations:
3461, 9485
3460, 9482
3460, 9480

**Comment by mrextremez** [comment]
According to osrs they spawn on the the 1st and 2nd lair. Is the queen on a different lair?

**Comment by Gptaqbc** [comment]
I had to go down 2 times to reach KQ.
