### ISSUE TITLE
Retribution and redemption doesnt do anything.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#241]

**Comment by mrextremez** [comment]
Last time I tested it redemption was working fine

**Comment by dginovker** [comment]
Can confirm neither work right now :C

![image](https://user-images.githubusercontent.com/32943174/70456658-8ce05380-1a7c-11ea-9397-77a9a7f30b88.png)

![image](https://user-images.githubusercontent.com/32943174/70456706-a7b2c800-1a7c-11ea-93d9-b1b7e3b8d394.png)

**Comment by dginovker** [comment]
This was fixed before actually, see these files: https://github.com/dginovker/2006rebotted/pull/207

**Comment by mrextremez** [comment]
Seems to only work against players
