### ISSUE TITLE
Some items cant be withdraw as noted when they should be.

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#244]
Black plateskirt (t) (ID 3472), black plateskirt (g) (ID 3473), adamant plateskirt (g) (ID 3475) so far.

**Comment by dginovker** [comment]
Using [Toms Suite](https://www.mediafire.com/file/pb5f84bybku5zo8/Toms_Suite.zip/file), it appears the things listed have `certID` and `certTemplateID` of `-1`:

![image](https://user-images.githubusercontent.com/32943174/70455529-776a2a00-1a7a-11ea-9d46-97df8b413a6f.png)

While notable items *seem* to have a certID of `ID+6` (i.e. Black Plateskirt (t) would be 3478) and a certTemplateID of 799. I think that's all that needs to be changed (+ some testing?). Cache can be found in `2006Redone fileserver` directory as well.

Image of note-able object:

![image](https://user-images.githubusercontent.com/32943174/70455726-c7e18780-1a7a-11ea-9b67-5f7e1bd5181a.png)

**Comment by mrextremez** [comment]
Any items that do this still other than the ones linked in main post?
