### ISSUE TITLE
Converting items to notes and notes to items by interacting with banker/booth

### ISSUE THREAD

**Issue by RedSparr0w** [dginovker/2006rebotted#248]
Cannot convert items to notes by using them on the banker/bank booth.
Cannot convert notes to items by using them on the banker/bank booth.

**Comment by mrextremez** [comment]
Not a bug that was added at a later date on osrs

**Comment by dginovker** [comment]
Yup. I think if we wanted that we would have to poll it

**Comment by Gptaqbc** [comment]
Closing this one?
