### ISSUE TITLE
Ring of life not working

### ISSUE THREAD

**Issue by RedSparr0w** [dginovker/2006rebotted#249]
Ring of life is not working as expected

**Comment by Gptaqbc** [comment]
public void applyringoflife() {
    		if (c.playerequipment[c.playerring] == 2570) {
    			if (c.playerlevel[3] > 0 && c.playerlevel[3] <= c.getlevelforxp(c.playerxp[3]) / 10 && c.underattackby > 0) {
    				int wildlvl = (((c.absy - 3520) / 8) + 1);
    				if (wildlvl < 20) {
    					c.getitems().deleteequipment(2570, c.playerring);
    					c.getpa().startteleport(config.falador_x, config.falador_y, 0, "modern");
    				}
    			}
    		}
    	}

**Comment by mrextremez** [comment]
This is what I use on my copy

`	public boolean savePlayer() {
		return (player.wildLevel < 20 && player.playerEquipment[ItemConstants.RING] == 2570 && player.playerLevel[3] > 0 && player.playerLevel[3] <= player.getLevelForXP(player.playerXP[3]) / 10 && player.underAttackBy > 0);
	}
	
	public void handleROL() {
		if (!savePlayer()) {
			return;
		}
		player.getItemAssistant().deleteEquipment(2570, ItemConstants.RING);
		player.getPlayerAssistant().startTeleport(3222, 3218, 0, "modern");
		player.getPacketSender().sendMessage("Your ring of life saves you.");
	}
	`
