### ISSUE TITLE
Issues/Bugs

### ISSUE THREAD

**Issue by Sch4ff3r** [dginovker/2006rebotted#255]
Smithing
[]Cannon balls can not be made using ammo mold on furnace 
as well as trying steel bar on furnace.
Steel bar on anvil to make cannon balls does pop up 
stating it is being made but doesn't make at all.

Rares
[]Bunny ears when wore, goes into weapon slot.
[]Yo-yo - able to equip-Doesn't do any animations when right clicking all opitions

Bank
[]When store items the option to put item in bank doesn't fully overlap the inventory, it stays inside the inventory where the outside hides the options.
-Depending where item is located in inventory-Need a full overlap for this.

Kitten/Cats 
ID: 1555(kitten) 1561(cat) 1556(kitten) 1562(cat) 
1557(kitten) 1563(cat) 1559(kitten) 1565(cat) 
1560(kitten) 1566(cat) 1558(kitten) 1564(cat)
Lazy cats all of them-Don't work just head drops
Wildy cat all of them-Don't work just head drops
[] When dropped kitten or cat-doesn't follow player
[]Catching rats is currently disabled
[X]Able to interact with kitten/cat
[X]Able to talk with kitten/cat

Items
[]Unholy Book-Pages 1, 2, 3, 4 Won't go into damaged book
[]Holy Book-Pages 1, 2, 3, 4 Won't go into damaged book
[]Book of balance-Pages 1, 2, 3, 4 Won't go into damaged book

[]Bearmask equips as a weapon instead of a helmet.

**Comment by Gptaqbc** [comment]
There are many issue in a single post. Could you split each issue into a post to facilitate dev's works?
