### ISSUE TITLE
Smithing Cannon balls

### ISSUE THREAD

**Issue by Sch4ff3r** [dginovker/2006rebotted#256]
- Cannon balls can not be made using ammo mold on furnace.
- Steel bar on anvil, an clicking cannon balls-Id 2 is made but doesn't show it made just a message stating it.
- When using ammo mold on furnace nothing happens.
- Steel bar on furnace nothing happens.

**Comment by Gptaqbc** [comment]
Can you give me mould, steel bar and cannonball IDs plz
