### ISSUE TITLE
Rares/Other Items

### ISSUE THREAD

**Issue by Sch4ff3r** [dginovker/2006rebotted#257]
- [ ] Bunny ears when wore, goes into weapon slot. Instead of going into helmet slot.

- [ ] Bearmask equips as a weapon instead of a helmet.

**Comment by Gptaqbc** [comment]
For bearmask: add 'Bearmask' in this method: private static String[] fullmask
in: Item.java
at line ~148

Like that: 
	private static String[] fullmask = { "full helm(t)", "full helm(g)", "full helm", "mask", "Verac's helm",
				"Guthan's helm", "Karil's coif", "mask", "Torag's helm", "Void", "helmet",
				"sallet", "Facemask", "Bearmask" };

**Comment by Gptaqbc** [comment]
I think the yo-yo issue should have its own thread because it's not the same fix needed.

**Comment by Sch4ff3r** [comment]
> I think the yo-yo issue should have its own thread because it's not the same fix needed. Let me know if you split the issues, I'll delete this comment. :)

New issue made for yo-yo

**Comment by Sch4ff3r** [comment]
> "Guthan's helm", "Karil's coif", "mask", "Torag's helm", "Void", "helmet",
> "sallet", "Facemask", "Bearmask" };

https://i.gyazo.com/c63646ffdbb975c8b129cff13fcb0479.png

**Comment by Gptaqbc** [comment]
Can't open the gyazo at work.

**Comment by DPSCryptic** [comment]
shows the bear mask in weapon slot with the full mask code besides it

**Comment by Gptaqbc** [comment]
So my fix isn't working?

**Comment by DPSCryptic** [comment]
and i think full mask means it covers the whole face. 
think it doesnt mean its head slot, think  --> public static int hats[] <-- is for head slot

**Comment by Gptaqbc** [comment]
Bear mask is a full mask though, that's why we add it there.

**Comment by DPSCryptic** [comment]
im not saying it doesnt :P it should be like that

**Comment by Gptaqbc** [comment]
Done
