### ISSUE TITLE
Only some of Kitten/Cats/Wildy Cat/Lazy Cat functionality works

### ISSUE THREAD

**Issue by Sch4ff3r** [dginovker/2006rebotted#258]
ID: 1555(kitten) 1561(cat) 1556(kitten) 1562(cat)
1557(kitten) 1563(cat) 1559(kitten) 1565(cat)
1560(kitten) 1566(cat) 1558(kitten) 1564(cat)
Lazy cats all of them-Don't work just head drops
Wildy cat all of them-Don't work just head drops

- [ ] When dropped kitten or cat-doesn't follow player
- [ ] Catching rats is currently disabled
- [X] Able to interact with kitten/cat
- [X] Able to talk with kitten/cat

**Comment by Gptaqbc** [comment]
So some cats works and some doesn't works? That's cool to know!
