### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by Sch4ff3r** [dginovker/2006rebotted#259]
[]Unholy Book-Pages 1, 2, 3, 4 Won't go into damaged book.
[]Holy Book-Pages 1, 2, 3, 4 Won't go into damaged book.
[]Book of balance-Pages 1, 2, 3, 4 Won't go into damaged book.

**Comment by Gptaqbc** [comment]
Out of the loop but I have a question. How were the books obtained in 2006?

**Comment by DPSCryptic** [comment]
same way as now i think

**Comment by DPSCryptic** [comment]
talk to the guy at the lighthouse i guess (the thingy at barbarian assault, across the water)
