### ISSUE TITLE
Bank overlay

### ISSUE THREAD

**Issue by Sch4ff3r** [dginovker/2006rebotted#260]
Bank
[]When store items the option to put item in bank doesn't fully overlap the inventory, it stays inside the inventory where the outside hides the options.
-Depending where item is located in inventory-Need a full overlap for this.

**Comment by dginovker** [comment]
Can you add a screenshot of what you mean?

**Comment by Gptaqbc** [comment]
You mean the right click menu not fitting in the inventory/interfaces? Yeah that shit is wack as hell!

**Comment by Sch4ff3r** [comment]
Yeah, thats what I mean. If possible looks like if its just overlayer'd the inventory it would work.

**Comment by dginovker** [comment]
I'm pretty sure this was an actual issue in real RS, since it's client sided and we are using a deobfuscated client. I'm willing to let this one pass. Any objections on close?

**Comment by Sch4ff3r** [comment]
[https://i.gyazo.com/a5ce77cb8cf45d2ac7b95fff5194c1af.png](url)

**Comment by Sch4ff3r** [comment]
> Can you add a screenshot of what you mean?

https://i.gyazo.com/a5ce77cb8cf45d2ac7b95fff5194c1af.png

**Comment by dginovker** [comment]
Yeah I don't think that's going to be fixed, just because of the context of it. Good report though.
