### ISSUE TITLE
Duel Arena

### ISSUE THREAD

**Issue by Sch4ff3r** [dginovker/2006rebotted#268]
https://i.gyazo.com/7403cb7d6a958b6c53e6257a4c17d086.png
Player A requests a duel
Player B Accepts duel
Player A accepts
Player B Accepts - The stake is closed
Player A left on the dueling menu waiting
No dueling

**Comment by Gptaqbc** [comment]
Oh yeah it's finally time to start working on dueling! Can't wait to stake all my cash tbh!

**Comment by Gptaqbc** [comment]
This can be closed.
