### ISSUE TITLE
Make ::commands open a quest interface instead of just a single message

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#274]
You can look at how `::highscores` (search project for `"highscores"`) does this for an easy template

**Comment by Gptaqbc** [comment]
Oh yeah that would be cool! It'd be useful as we'll be able to add a lot of information i.e shop commands.

**Comment by Gptaqbc** [comment]
This is how ::highscores works:

 case "highscores":
1. Save players informations (Not needed in the actual context)
2. Create var Highscores with the needed information (This can be replaced by strings to display the information needed)
> HighscoresHandler hs = new HighscoresHandler();
                                String[] highscores = new String[]{
                                        "Top 5 Total Level:",
                                        hs.getRank(player, 0, "level"),
                                        ...
                                        "",
                                        "Top 5 Wealthiest Players:",
                                        hs.getRank(player, 0, "gold"),
                                        ...
                                        "",
                                        "Top 5 Highest Total Damage:",
                                        hs.getRank(player, 0, "damage"),
                                        ...
                                };
3. Clears old lines that were inserted last time sendFrame126 was used:
> for (int i = 8144; i < 8195; i++) player.getPacketSender().**sendFrame126("", i)**;

4. Specify lineNumber (Really have no idea why the number is 8147)
> int lineNumber = 8147;

5. Add the string arrays from step 2 to the Frame126
> for (String line : highscores){
                                        System.out.println(line + " - " + lineNumber);
                                        player.getPacketSender().sendFrame126(line, lineNumber++);
                                }

6. Display the interface in the player's client
> player.getPacketSender().showInterface(8134);
