### ISSUE TITLE
Smelting steel bars not working

### ISSUE THREAD

**Issue by Manco-dev** [dginovker/2006rebotted#275]
Smelting steel bars is not working, the ores disappear but the bar doensn't get created. Tested it in Al-Kharid and Falador.

![smelting_steel](https://user-images.githubusercontent.com/58816528/70716794-54937c00-1ced-11ea-98e6-ca8a11203b19.gif)

**Comment by Gptaqbc** [comment]
Can you give me coal, iron ore and steel bar IDs plz

**Comment by Manco-dev** [comment]
Coal is 454 and iron 441. I'm not sure about steel bars because I was not able to create it.

**Comment by RedSparr0w** [comment]
I cannot seem to smith any items with the furnace currently, tried iron, and steel.
It takes the items, but doesn't give you a bar.
Super heating still works fine though.
