### ISSUE TITLE
Adding toggeable snow for Christmas

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#276]
https://www.rune-server.ee/runescape-development/rs2-server/help/452302-pi-making-snow.html

Also, add a check to know if it's december to this^ and snowy ground:

Code:
import java.util.Calendar;
import java.util.GregorianCalendar;

public class DateAndTime {

	public static String getTodaysDate() {
		Calendar date = new GregorianCalendar();
		return date.get(Calendar.DAY_OF_MONTH) + "."
				+ (date.get(Calendar.MONTH) + 1) + "."
				+ date.get(Calendar.YEAR);
	}

}

Code:
				if (DateAndTime.getTodaysDate().contains(".12")) {
					if (anInt390 == 0x35720A || anInt390 == 0x50680B
							|| anInt390 == 0x78680B || anInt390 == 0x6CAC10
							|| anInt390 == 0x819531)
						anInt390 = 0xffffff;
				}

**Comment by mrextremez** [comment]
Wasn't this already added? Other than the date part

**Comment by Gptaqbc** [comment]
Some stuff missing + snow interface

**Comment by Gptaqbc** [comment]
If(c.inarea()) {
getPA().walkableInterface(11877);
}

**Comment by Gptaqbc** [comment]
Doooone - gotta push
