### ISSUE TITLE
Shop Bug

### ISSUE THREAD

**Issue by Sch4ff3r** [dginovker/2006rebotted#277]
https://i.gyazo.com/c00173fffe3c913bb7380c176254e7ba.png
::cshop ::closeshop Works 100%
Collecting gp from shop haven't tested due to crash
When trading char owner shop, it pulls up the shop but it crashes right after it is opened.

**Comment by Gptaqbc** [comment]
... You have a lot of problem on your side that's for sure xD

**Comment by RedSparr0w** [comment]
Cannot replicate the issue..

Can you please attach the error log, it will make it a ton easier to figure out why you are crashing.

**Comment by mrextremez** [comment]
Cannot replicate this myself
