### ISSUE TITLE
strange numbers in smelthing interface over mithril bar

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#278]
Wack stuff is happening when the Frame is displayed in the interface.

**Comment by RedSparr0w** [comment]
Could you please attach a screenshot.

**Comment by RedSparr0w** [comment]
The number that appears seems to be the xp needed for your next level of runecrafting.

**Comment by RedSparr0w** [comment]
![image](https://user-images.githubusercontent.com/7288322/70752654-ec4da480-1d97-11ea-9501-ad599b85681d.png)
