### ISSUE TITLE
Getting 32 bit warning message on 64 bit version

### ISSUE THREAD

**Issue by RedSparr0w** [dginovker/2006rebotted#282]
![image](https://user-images.githubusercontent.com/7288322/70756612-e8268480-1da1-11ea-8c2c-ab5c2ad4c8b4.png)

![image](https://user-images.githubusercontent.com/7288322/70756609-e2c93a00-1da1-11ea-9e32-0e99d8bbb670.png)

**Comment by dginovker** [comment]
It's this line that's faulty: https://github.com/dginovker/2006rebotted/blob/master/2006Redone%20Client/src/Game.java#L11539

Guess it only works on Linux :tada:
