### ISSUE TITLE
Party room chest and bank seem to get confused, players lose items they try to bank after opening party chest

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#288]
Steps: 

1) Go to Camelot party room, try to put things in, it will say it's disabled
2) Go to a bank, try to put things in, they will go byebye

**Comment by mrextremez** [comment]
Will fix when I have time. Thats not good though!

**Comment by Ethan07Scape** [comment]
first obect click on chest sets variable inPartyRoom true.

Easy fix, should take 1 min

**Comment by Gptaqbc** [comment]
"if" missing in title btw
