### ISSUE TITLE
Mud Battlestaff doesn't work as runes

### ISSUE THREAD

**Issue by Gargalhar** [dginovker/2006rebotted#297]
Visually it appears as if you have infinite water and earth runes but if you try to cast a spell that requires them it will say that you don't have the runes. I have not tried other staves.

**Comment by Gptaqbc** [comment]
Item ID?

**Comment by Gargalhar** [comment]
6562

**Comment by Gptaqbc** [comment]
Thanks! Should be fixed, gotta test it when I get home.

**Comment by RedSparr0w** [comment]
Same problem with enchanting.

Was fixed for superheat awhile ago.
