### ISSUE TITLE
When equipping an item the weight of the player changes

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#309]

**Comment by RedSparr0w** [comment]
Are you able to provide an example?
When you equip/unequip items, it re calculates your inventory/what you are wearing.
So if anything it should correct your weight.

**Comment by Gptaqbc** [comment]
Have a lot of stuff in your invent so you weight like 20+ then equip a staff. Your weight will go down. 

That's what I did.
