### ISSUE TITLE
Fight Caves

### ISSUE THREAD

**Issue by MitchvanWijngaarden** [dginovker/2006rebotted#310]
The Fight Caves are incredibly buggy. I have screenshotted most of the problems, and prioritized the issues within the attached list of to-do items. 

- [ ] Fight caves are not properly instanced!
![image](https://user-images.githubusercontent.com/19310541/71308186-b6449c00-23f9-11ea-9dbd-fae1f80ccc8b.png)
You can drop potions/and or other supplies for other players.

- [ ] Stop NPC's from clipping in eachother. 
![image](https://user-images.githubusercontent.com/19310541/71308091-4255c400-23f8-11ea-969d-95bdb0517dcc.png)

- [ ] Fix waves starting before all NPC's are cleared
![image](https://user-images.githubusercontent.com/19310541/71308083-205c4180-23f8-11ea-999a-c7306163d0f6.png)
- [ ] Fix TzTok-Jad attacks in melee range to not instantly damage the player as soon as the animation starts.
- [ ] Fix TzTok-Jad's second phase, healers do not heal.

- [ ] Fix Tok-Xil (level 90) and Ket-Zek (level 360) not attacking players when they are not in a straight line of sight
![image](https://user-images.githubusercontent.com/19310541/71308106-85179c00-23f8-11ea-9278-b8b7bf1535c6.png)

- [ ] Use NPC size for NPC pathfinding / allow safespotting.
![image](https://user-images.githubusercontent.com/19310541/71308089-3833c580-23f8-11ea-98dc-b4baf7a840b6.png)

- [ ] Fix NPC spawns to be more OSRS like.

**Comment by mrextremez** [comment]
I will look into some of these thanks!

**Comment by Jamix77** [comment]
A cheap fix for the itmes appearing on multiple Zs is to have the items correct Z stored on server and when a player attempts to pick up an item not for them it should say so and not let them pick it up. Although there is probably a better way to fix anyways.

**Comment by Gptaqbc** [comment]
@Jamix77 Well the appropriate fix would be to make the item not appear at all on other Z. So other players wouldn't even see the items.

**Comment by Gptaqbc** [comment]
Here is a rip off of a working Fight Cave: https://www.rune-server.ee/runescape-development/rs2-server/help/490132-pi-fight-caves-wave-spawning.html

It could be use to see what we are missing.

**Comment by Jamix77** [comment]
I had a look through the 2006 code and I couldn’t see that sort of support for multiple Zs for items already in the code and the packets client side don’t have Z factors so that needs to be done server side, seems like some effort tbh, I can’t do it anytime soon but If you’d like to give it a go you could, I’m away for at least the next 5 days so I could look into it further when I get back if it hasn’t already been done

**Comment by Gptaqbc** [comment]
I'll be focusing on server side pathing verification in the following days :P 

Yeah pretty sure that if we add the Z coord to the item as you said. It'll most likely make it non visible on other Z too!
