### ISSUE TITLE
Woodcutting rates are imbalanced.

### ISSUE THREAD

**Issue by MitchvanWijngaarden** [dginovker/2006rebotted#32]
Chopping oak results in +- 900 logs an hour
- Woodcutting exp: 37.5 * 900 = 33750 exp an hour
- Fletching exp: 25 * 900 = 22500 exp an hour.

Chopping willows results in +- 200 logs an hour
- Woodcutting exp: 67.5 * 200 = 13500 exp an hour
- Fletching exp: 41.5 * 200 = 8300 exp an hour

Chopping maples result in +- 90 logs an hour
- Woodcutting exp: 90 * 100 = 9000 exp an hour
- Fletching exp 58.3  * 90 = 5247 exp an hour

Rates with 60 woodcutting, steel axe.

**Comment by mrextremez** [comment]
Oaks were set on the wrong respawn speed so that’s why the exp was so much higher I have adjusted that in my last pr so once that goes live it should be a bit more realistic
