### ISSUE TITLE
Sending the cooking >1 option more than once seems to accellerate the speed at which you cook food

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#329]
1.Use raw fish on range/fire
2.Wait till it cooks a fish...
3.Do step 1 again

Result: You'll be cooking food faster than normal speed.

**Comment by mrextremez** [comment]
The event might be overlapping if that is the case

**Comment by Gptaqbc** [comment]
Yeah it's similar to arrow making that we were able to stack unlimited Cycle or whatever they are called.

But what is strange is that I was only able to do it twice.

**Comment by MitchvanWijngaarden** [comment]
You can do this on OSRS as well with some foods if you are fast enough. 1-tick karambwans and 3-tick cooking used to be a thing before they added in the cook-all interface.

**Comment by Gptaqbc** [comment]
@MitchvanWijngaarden  I'm not talking about this at all though. Try it. You can launch multiple action cycle like ArrowMaking.java class used to do.

**Comment by MitchvanWijngaarden** [comment]
Potential overlap with #358 ?

**Comment by Gptaqbc** [comment]
No because the code is in seperate classes so it's 2 issues.

**Comment by Gptaqbc** [comment]
@mrextremez  This should be fixed, right?

**Comment by mrextremez** [comment]
Yeah @Gptaqbc
