### ISSUE TITLE
You can cook food far away from ranges using Use-Item-On in Script Factory

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#331]
For example: 

At Camelot bank, run this in script factory with a inventory full of raw lobsters:
Use-item-on(378,2728,62)
Sleep(500)
Click-xy(253,425,1)
Click-xy(253,425,0)
Sleep(15000)

**Comment by mrextremez** [comment]
Simple fix would be to add a distance check before you can cook them

**Comment by Gptaqbc** [comment]
Yeah, to fix this, the solution used to prevent this happening with thieving stall by @mikeysasse can be used.
