### ISSUE TITLE
Player is dcing when using the Magic short/long bow special attack

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#333]

**Comment by mrextremez** [comment]
Does it throw an error?

**Comment by Gptaqbc** [comment]
Nothing. Dragon dagger specs works fine too.

**Comment by mrextremez** [comment]
I tested it locally and was not able to reproduce this bug.

**Comment by Gptaqbc** [comment]
For fucks sake I forgoit to mention it was the specs that dc the player.
