### ISSUE TITLE
Draggon daggers are 1gp in the shop at Zaniris

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#334]
Shop name: Jukats Sword Shop

**Comment by Sch4ff3r** [comment]
2x always in stock
Dragon dagger | 2 | Price to buy from shop 30,000 | Price to sell at shop 18,000

**Comment by Gptaqbc** [comment]
Stock is changed. To change item price, update the value in the itemdef.gsu file.

**Comment by Gptaqbc** [comment]
@dginovker didnt you change how the item prices were stored?

**Comment by dginovker** [comment]
Yeah they're now in itemdefs.json (might be itemdef.json). 50/50 this issue is already fixed
