### ISSUE TITLE
Create Voting Skill Tree (Community WIP)

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#34]
Anyone can edit the document, if it gets brigaded I can revert history. https://drive.google.com/file/d/1MKDvZplamWb9Ed-nDU5cQdKLUowEBXjD/view?usp=sharing

Share thoughts and ideas either here or in the Discord.

**Comment by Gptaqbc** [comment]
What is needed for this issue to be closed?

**Comment by dginovker** [comment]
Tbh someone with big ideas who doesn't know how to code
