### ISSUE TITLE
Rune essence mining - if another players gets essence all other players will restart mining

### ISSUE THREAD

**Issue by MitchvanWijngaarden** [dginovker/2006rebotted#351]
If a player mines a rune essence, the mining variable of all other players will reset. The player with the highest mining level or pid will get the essence, the other players will not.

PR #349 fixes this issue.

**Comment by Gptaqbc** [comment]
Create a new post for the remaining issue plz.

**Comment by MitchvanWijngaarden** [comment]
> 
> 
> Create a new post for the remaining issue plz.

Done. See #358
