### ISSUE TITLE
No Whip Animation

### ISSUE THREAD

**Issue by Sch4ff3r** [dginovker/2006rebotted#352]
Whip Animation on monsters doesn't show up.

**Comment by Jamix77** [comment]
Which monsters in particular?

**Comment by Gptaqbc** [comment]
All monsters as it's not coded.

**Comment by Gptaqbc** [comment]
In specials.java line 108 method activateSpecial doesnt support NPC because in a fight with a NPC the o var is null so this never happens:

					if (o != null)
					{
						o.gfx0(SA.getGfx1());
					}

**Comment by Gptaqbc** [comment]
Oh I got it! Add this before the line 108:

			if(Server.npcHandler.npcs[i] != null) {
				Server.npcHandler.npcs[i].gfx100(341);
			}

If NPC var isn't null it'll apply the GFX to it.

EZPZ
