### ISSUE TITLE
Emote animations doesn't work

### ISSUE THREAD

**Issue by TheAndersMadsen** [dginovker/2006rebotted#355]

**Comment by mrextremez** [comment]
Can you expand on that? Like the emotes tab?

**Comment by TheAndersMadsen** [comment]
Yup! If you press any of the available emotes, they don't work

**Comment by TheAndersMadsen** [comment]
This is only on the Parabot client. Emotes work otherwise.

**Comment by TheAndersMadsen** [comment]
Reopened since it is problematic due to botting

**Comment by mrextremez** [comment]
@Gptaqbc  or @dginovker

**Comment by Gptaqbc** [comment]
They works perfectly for me.

**Comment by mrextremez** [comment]
Can be closed unless people are still having issues
