### ISSUE TITLE
When you talk with NPC's, the text isn't aligned

### ISSUE THREAD

**Issue by TheAndersMadsen** [dginovker/2006rebotted#356]

**Comment by MitchvanWijngaarden** [comment]
Text also overflows on multiple occasions. See rune mysteries quest for example dialogue.

**Comment by mrextremez** [comment]
Show me where it isn't aligned and when it overflows and I will fix

**Comment by TheAndersMadsen** [comment]
For example all the dialogues in the rune mysteries quests is a good example

**Comment by Gptaqbc** [comment]
@mrextremez  what is the way to fix this? Do we simply have to edit the dialogues so they have less character?

**Comment by mrextremez** [comment]
As of now that is the way to fix that currently yes
