### ISSUE TITLE
There is a tab next to the smiley icon you can press even though it doesn't exist

### ISSUE THREAD

**Issue by TheAndersMadsen** [dginovker/2006rebotted#357]

**Comment by mrextremez** [comment]
I can disable this if needed, although I don't think this a major bug

**Comment by TheAndersMadsen** [comment]
I mean, this is just bugs that I find. I isn't a major bug, but it sure does make the whole thing feel a little more non-buggy if fixed I guess - the closer to 1:1, the better imo

**Comment by mrextremez** [comment]
I fixed can be closed
