### ISSUE TITLE
Can't teleport from MB, something weird happens when you run ::stuck

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#370]
https://cdn.discordapp.com/attachments/577599674417020928/673923902107418633/unknown.png

https://cdn.discordapp.com/attachments/577599674417020928/673924599544545280/unknown.png

**Comment by mrextremez** [comment]
Just tested this myself and did not encounter the issue. Any more info on how to make it happen?

**Comment by mrextremez** [comment]
@dginovker still a bug?

**Comment by dginovker** [comment]
Someone else reported it. There may have been more to it, but I'm fine with a close since we can't reproduce.
