### ISSUE TITLE
Pretty hard to safespot giants/dragons, walk through walls.

### ISSUE THREAD

**Issue by AgilityV2** [dginovker/2006rebotted#46]
Hill giants, fire giants, mossgiants just walk through safespots.
Blue dragon under heroes guild walk through gate, and the safespot to the north

**Comment by Gptaqbc** [comment]
I think this is fixed... I can safespot stuff right now.

**Comment by Gptaqbc** [comment]
Any update for this issue?

**Comment by dginovker** [comment]
I think it's good as well. Going to close for now, we can create a new one with more specifics if anyone has a problem :)
