### ISSUE TITLE
Diagonal Combat Bug

### ISSUE THREAD

**Issue by mrslayer01** [dginovker/2006rebotted#47]
Seems to be a common thing with the revision he used, but you can just step 1 square diagonally and npcs won't attack back which you can just range them.

**Comment by mrextremez** [comment]
Issue has to do with npc attack clipping

**Comment by Gptaqbc** [comment]
Here's a potential solution: https://www.rune-server.ee/runescape-development/rs2-server/snippets/688419-npc-safespot-angle-fix.html

**Comment by Gptaqbc** [comment]
Alright, seems like what I found will fix our problem. I'll implement it tonight when I get home.

**Comment by Gptaqbc** [comment]
In NPCHandler.java (line 1038):
		if (goodDistance(npcs[i].getX(), npcs[i].getY(), playerX, playerY,
				distanceRequired(i))) {
			return;
		}

This is what fucks it up. It's about the distanceRequired. I'll look closer at it when I have more time!
