### ISSUE TITLE
Fletching Crash

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#51]
![image](https://user-images.githubusercontent.com/32943174/66686437-7751d780-ec4d-11e9-9a37-d563882caa46.png)

**Comment by mrextremez** [comment]
Can you replicate issue?

**Comment by RedSparr0w** [comment]
Hasn't happened since #52 was implemented

**Comment by RedSparr0w** [comment]
I would say this is safe to close now?
