### ISSUE TITLE
Gate at Ice Giants in Wilderness doesn't work

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#6]
Hacky job like just deleting the Gate to make it functional is fine. The gate to the East doesn't work either.

**Comment by mrextremez** [comment]
Coords?

**Comment by RedSparr0w** [comment]
These 6 gates don't work:
```
    new Tile(2947, 3903, 0),
    new Tile(2948, 3903, 0),
    new Tile(3224, 3903, 0),
    new Tile(3225, 3903, 0),
    new Tile(3336, 3895, 0),
    new Tile(3337, 3895, 0)
```

**Comment by mrextremez** [comment]
> These 6 gates don't work:
> 
> ```
>     new Tile(2947, 3903, 0),
>     new Tile(2948, 3903, 0),
>     new Tile(3224, 3903, 0),
>     new Tile(3225, 3903, 0),
>     new Tile(3336, 3895, 0),
>     new Tile(3337, 3895, 0)
> ```
> 
> _3 pairs of 2_

I will fix them if I have time

**Comment by RedSparr0w** [comment]
Sorry, it's actually on these 4:
```java
    new Tile(2947, 3904, 0),
    new Tile(2948, 3904, 0),
    new Tile(3224, 3904, 0),
    new Tile(3225, 3904, 0),
```

**Comment by Gptaqbc** [comment]
We need to have a list in here that we can add all the objects that aren't working properly so the information is not splitted between discord and many issues.
