### ISSUE TITLE
Client freeze when teleporting/walking to Ardougne

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#60]
I noticed that when managing my bots at Ardougne. When trying to teleport with my main the client kept freezing so I tried walking there, same thing: client freeze on the tile in front of the entrace to Ardougne. 

The only reason I can think of is because of my 10 bots that are abusing the silver stall from the bank. Yeah, from the bank. The thieving action can be executed from the bank.

I think it's related to my bots because before setting it up Ardougne was fine. :)
I'll check it out and try to provide more info.

**Comment by dginovker** [comment]
Now part of issue #79
