### ISSUE TITLE
Add update and restart commands to 2006ReBot

### ISSUE THREAD

**Issue by Dark98** [dginovker/2006rebotted#63]
Add these commands to anyone with Developer privilages

**Comment by mrextremez** [comment]
Update command already exists

**Comment by dginovker** [comment]
Yup you just need an admin acc. Dark you can admin yourself on the server, seeing as you already have access - Just make sure it has a secure password.

**Comment by Dark98** [comment]
@mrextremez @dginovker I mean add them to the discord bot :p

**Comment by dginovker** [comment]
Oh that's sick

**Comment by Dark98** [comment]
Didn't think this through properly at the time, it's not really possible to start the server again once it's been shutdown because the discord bot is integrated into the server 🤦‍♂️
