### ISSUE TITLE
NPC 178 Black Knight is aggressive when it shouldn't be

### ISSUE THREAD

**Issue by MitchvanWijngaarden** [dginovker/2006rebotted#7]
![afbeelding](https://user-images.githubusercontent.com/19310541/66259039-e1313380-e7ac-11e9-9f66-58b0cedcd499.png)
It's also masochistic, it doesn't fight back once you escape it's aggression zone once.

**Comment by dginovker** [comment]
Have you considered writing a bot to camp the black knight instead?

**Comment by MitchvanWijngaarden** [comment]
no

**Comment by dginovker** [comment]
Closing issue until further comment.

**Comment by mrextremez** [comment]
I’m pretty sure hiss aggressiveness is based on your combat level

**Comment by Gptaqbc** [comment]
Yes but it should be aggresive anyway IIRC

**Comment by Gptaqbc** [comment]
Why was this reopened?

**Comment by Gptaqbc** [comment]
This can be solved by changing the NPC spawned at Draynor by ID 179 and modifying this NPC to be un-aggressive.

**Comment by Gptaqbc** [comment]
But someone have to confirm if this is a real issue or if it was like that in 2006.

**Comment by Gptaqbc** [comment]
Aight it'S confirmed it wasn't aggro. To fix, remove 178 from the array of int named: AGGRESSIVE_MONSTERS

**Comment by Gptaqbc** [comment]
Fixed
