### ISSUE TITLE
Fix Gates and Doors so that when they're added/removed many times in a row, clients near them don't get packed bombed

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#79]
**Situation**: It's pretty much confirmed now that the way gates and doors work lag out clients, since clicking on a gate/door will "delete" the original and replace it with a door in the new location. The problem is the door isn't properly deleted, so doing this enough times will cause a player to lag out when entering the area.

**Comment by mrextremez** [comment]
Is there a specific action that sets off the lag?

**Comment by dginovker** [comment]
Not sure. I'm personally testing a bunch of bots opening and closing doors under the HAM camp: https://i.imgur.com/d1I9Rok.png

**Comment by Gptaqbc** [comment]
Wow, nice test @dginovker. That's some valuable informations right here!

**Comment by mikeysasse** [comment]
Caused by object packet 85 and 101, bad code is causing objects to be added but not be removed which overloads the client with unnecessary packets. Temporary solution would be to remove all game objects at the specific location with the same type when adding a new game object.

**Comment by dginovker** [comment]
Closed in #170 , thanks to @mikeysasse for the fix <3
