### ISSUE TITLE
Can interact with objects using raw packets that you're not beisde

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#80]
```
if (player.goodDistance(player.objectX + player.objectXOffset, player.objectY + player.objectYOffset, player.getX(), player.getY(), player.objectDistance)) {
                player.turnPlayerTo(player.objectX, player.objectY);
                FirstClickObject.firstClickObject(player, player.objectId, player.objectX, player.objectY);
            } else {
                player.clickObjectType = 1;
                   CycleEventHandler.getSingleton().addEvent(player, new CycleEvent() {
                        @Override
                        public void execute(CycleEventContainer container) {
                        if (player.clickObjectType == 1 && player.goodDistance(player.objectX + player.objectXOffset, player.objectY + player.objectYOffset, player.getX(), player.getY(), player.objectDistance)) {
                            player.turnPlayerTo(player.objectX, player.objectY);
                            FirstClickObject.firstClickObject(player, player.objectId, player.objectX, player.objectY);
                            container.stop();
                        }
                        if (player.clickObjectType > 1 || player.clickObjectType == 0) {
                            container.stop();
                        }
                    }

                    @Override
                    public void stop() {
                        player.clickObjectType = 0;
                    }
                }, 1);
            }
            break;
```

Apparently this code fixes it ^

**Comment by Gptaqbc** [comment]
Sweet code!

**Comment by mrextremez** [comment]
This code that I posted belongs in click object.java below the switch statement on first click

**Comment by Dark98** [comment]
> ```
> if (player.goodDistance(player.objectX + player.objectXOffset, player.objectY + player.objectYOffset, player.getX(), player.getY(), player.objectDistance)) {
>                 player.turnPlayerTo(player.objectX, player.objectY);
>                 FirstClickObject.firstClickObject(player, player.objectId, player.objectX, player.objectY);
>             } else {
>                 player.clickObjectType = 1;
>                    CycleEventHandler.getSingleton().addEvent(player, new CycleEvent() {
>                         @Override
>                         public void execute(CycleEventContainer container) {
>                         if (player.clickObjectType == 1 && player.goodDistance(player.objectX + player.objectXOffset, player.objectY + player.objectYOffset, player.getX(), player.getY(), player.objectDistance)) {
>                             player.turnPlayerTo(player.objectX, player.objectY);
>                             FirstClickObject.firstClickObject(player, player.objectId, player.objectX, player.objectY);
>                             container.stop();
>                         }
>                         if (player.clickObjectType > 1 || player.clickObjectType == 0) {
>                             container.stop();
>                         }
>                     }
> 
>                     @Override
>                     public void stop() {
>                         player.clickObjectType = 0;
>                     }
>                 }, 1);
>             }
>             break;
> ```
> 
> Apparently this code fixes it ^

Has anyone implemented this yet? If not I will when home tonight

**Comment by Gptaqbc** [comment]
Wasn't tried I think!

**Comment by mikeysasse** [comment]
should have been resolved here https://github.com/dginovker/2006rebotted/commit/a9d45373e0ba39808fdb8ed70f5e99d33a46244d
