### ISSUE TITLE
Sheep shearer shows wrong name before completion

### ISSUE THREAD

**Issue by RedSparr0w** [dginovker/2006rebotted#85]
![image](https://user-images.githubusercontent.com/7288322/67349107-769d3780-f5a3-11e9-92c3-8b9d4e0a0392.png)
![image](https://user-images.githubusercontent.com/7288322/67349114-80269f80-f5a3-11e9-91c1-fc2fae6e65c8.png)

**Comment by mrextremez** [comment]
Whoever added black knights fortress incorrectly gave it the quest tab id of sheep shearer.
