### ISSUE TITLE
Teleother spells not working

### ISSUE THREAD

**Issue by Dark98** [dginovker/2006rebotted#87]
it says "this player is not in the wilderness"

**Comment by Gptaqbc** [comment]
Here's some documentation about how to implement it correctly: https://www.rune-server.ee/runescape-development/rs2-server/snippets/417582-adding-teleother-project-insanity.html

I don't know if we use the same base as Project Insanity, but I'll be taking a look at it tonight.

**Comment by mrextremez** [comment]
Wherever it says this player is not in the wild add a check to not show that if they are using teleother

**Comment by Gptaqbc** [comment]
Working on it!

**Comment by Dark98** [comment]
fixed by @Gptaqbc
