### ISSUE TITLE
Tzhaar area need some works done

### ISSUE THREAD

**Issue by Gptaqbc** [dginovker/2006rebotted#90]
The NPCs aren't using the correct combat style and they don't drop tokkuls, the shops are selling for tokkuls but buying for gps.

**Comment by mrextremez** [comment]
Which npcs are not working? Everyone that I tested was working fine. Send npc ids here and i can fix them

**Comment by RedSparr0w** [comment]
Shop fixed in #121 by @mrextremez

**Comment by mrextremez** [comment]
can this be closed or do the npcs still need work?

**Comment by Gptaqbc** [comment]
It can be closed!
